### PR TITLE
feat: add devcontainers-extra features to index

### PR DESCRIPTION
**Pull request by koralowiec**
## What type of PR is this?

- [x] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Related Issues

- Related Issue #
- Closes #

## Description

Added [Dev Container Features by devcontainers-extra](https://github.com/devcontainers-extra/features) which is fork of [devcontainers-contrib/features](https://github.com/devcontainers-contrib/features) (that collection is no longer maintained, and was removed from the collection index #451)

### Collection checklist
_If your PR contributes a new collection, please utilize this checklist:_
- [x] Collection name
- [x] Maintainer name
- [x] Maintainer contact link (i.e. link to a GitHub repo, email)
- [x] Repository URL
- [x] OCI Reference
- [x] I acknowledge that this collection provides new functionality, distinct from the existing collections part of this index.

### CODE REVIEW

**Comment by koralowiec** [comment]
Hi @samruddhikhandale, and sorry for pinging 😅 Is there anything that needs to be changed to get the collection to the index?

**Review by samruddhikhandale — APPROVED** [review]
Apologies, look like this PR slipped through the cracks. 

420 new Features? That's amazing and commendable. Great to see that you are taking responsibility for maintaining Features from devcontainers-contrib/features

**Comment by evilhamsterman** [comment]
@samruddhikhandale you should revert this merge. This was removed from the list in #451 because the project is misleadingly named and appears to have been abandoned. Many of them are broken an no longer work.

**Comment by evilhamsterman** [comment]
Sorry I missed it's a fork someone made of the original.

**Pull request merged**
