### PR TITLE
Features clarification to match the spec

### PR DESCRIPTION
**Pull request by bamurtaugh**
Updates to match the changes in https://github.com/devcontainers/spec/pull/72.

### CODE REVIEW

**Review by joshspicer — APPROVED** [review]

**Review by joshspicer — COMMENTED** [review]
Needs to be re-synced before merging!

**Comment by bamurtaugh** [comment]
Thanks @joshspicer! Just updated with the latest.

**Comment by bamurtaugh** [comment]
Also just updated based on https://github.com/devcontainers/spec/pull/77/files.

**Comment by bamurtaugh** [comment]
@joshspicer just made the latest changes to match your merged PR, would love another review!

**Comment by Chuxel** [comment]
Just a FYI @bamurtaugh that I merged in https://github.com/devcontainers/spec/pull/84 with updates so not sure if that should be done in this PR or another one.

**Review by alexdima — APPROVED** [review]

**Review by joshspicer — APPROVED** [review]

**Comment by bamurtaugh** [comment]
Thanks @Chuxel, I'm going to work on a new PR to focus on these changes!

And thanks all for the reviews and approvals, will merge this one now.

**Pull request merged**
