### PR TITLE
Update collection-index.yml

### PR DESCRIPTION
**Pull request by texmachina**
Add Skyramp tooling to Collections

### CODE REVIEW

**Review by samruddhikhandale — APPROVED** [review]
Looks great, thank you!

**Comment by texmachina** [comment]
@samruddhikhandale -- much thanks! We had a formatting typo on our side and have updated our feature. How/when does collection crawling take place to update the enumerated features listed?

**Comment by samruddhikhandale** [comment]
Hi @texmachina, the crawler runs once per day (automatically), and we also manually run it when anyone adds a new entry to the index. 

I ran the crawler now, let me know if there are any issues.

**Comment by texmachina** [comment]
@samruddhikhandale - looks good! Thanks again for all of your help. 😄

**Pull request merged**
