### PR TITLE
Add Integrated Circuit Design Devcontainer Template

### PR DESCRIPTION
**Pull request by curtisma**
Add the Viper open-source integrated circuit dev container template.

### CODE REVIEW

**Review by samruddhikhandale — COMMENTED** [review]
Thanks! @curtisma can you help resolve the merge conflict?

**Comment by curtisma** [comment]
> Thanks! @curtisma can you help resolve the merge conflict? 

Yeah, I will do that this evening.
Thanks!

**Comment by curtisma** [comment]
Ok, the merge conflict is fixed to include both items.
It should be good to go @samruddhikhandale.

**Review by samruddhikhandale — APPROVED** [review]
Thanks ⚡

**Pull request merged**
