### PR TITLE
Add command runner

### PR DESCRIPTION
**Pull request by wxw-matt**
A feature that can run any valid shell commands. 
For example:
```jsonc
"ghcr.io/wxw-matt/devcontainer-features/command_runner:latest": {
        "command1": "apt-get update -y",
        "command2": "apt-get install -y vim telnet",
	"command3": "rm -rf /var/lib/apt/lists/*"
}
```

### CODE REVIEW

**Review by samruddhikhandale — COMMENTED** [review]
https://github.com/devcontainers/devcontainers.github.io/pull/184 already added an entry to the https://github.com/wxw-matt/devcontainer-features collection. 

Probably, this PR is created on accident?

**Comment by wxw-matt** [comment]
Hi @samruddhikhandale thanks for merging the scrip runner. The **command runner** is another one which helps developers run shell commands much more easily and quickly.

**Comment by samruddhikhandale** [comment]
From https://containers.dev/features, we only need to add the `ociReference` of collection metadata artifact only once. Both the Features can be seen in the index 👇 

image

**Comment by wxw-matt** [comment]
Wow, that's great. I didn't realise that. Then I am happy to close this PR.

**Pull request closed without merging**
