### PR TITLE
add datascience-py-r template

### PR DESCRIPTION
**Pull request by minsa110**

### CODE REVIEW

**Comment by minsa110** [comment]
+@alexkyllo

**Comment by minsa110** [comment]
cc\ @bamurtaugh

**Review by bamurtaugh — APPROVED** [review]
Thanks so much @minsa110! 

@samruddhikhandale @joshspicer - would appreciate a second (or third) set of eyes from either of you :)

**Review by samruddhikhandale — APPROVED** [review]
Looks great, thank you! ⚡

**Pull request merged**
