### PR TITLE
Add ROS2 devcontainer template

### PR DESCRIPTION
**Pull request by tonynajjar**
## What type of PR is this?

- [x] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Description

Adds ROS2 devcontainer template

### CODE REVIEW

**Review by samruddhikhandale — DISMISSED** [review]
Looks good, thanks!

**Comment by samruddhikhandale** [comment]
@tonynajjar Can you help resolve the merge conflicts, then we are good to merge? thanks!

**Comment by tonynajjar** [comment]
@samruddhikhandale done

**Review by samruddhikhandale — APPROVED** [review]
Thanks!

**Pull request merged**
