### PR TITLE
Add Julia Language Templates collection

### PR DESCRIPTION
**Pull request by davidanthoff**
CC @eitsupi

### CODE REVIEW

**Comment by davidanthoff** [comment]
Presumably we should delete all Julia related stuff from https://github.com/microsoft/vscode-dev-containers once this here is merged, right?

**Review by samruddhikhandale — APPROVED** [review]
Nice, thanks! 🚀

**Comment by eitsupi** [comment]
@samruddhikhandale Thanks for merging.
Could you remove the old Julia Template from https://github.com/microsoft/vscode-remote-release as like R and Swift?

**Comment by samruddhikhandale** [comment]
> @samruddhikhandale Thanks for merging. Could you remove the old Julia Template from https://github.com/microsoft/vscode-remote-release as like R and Swift?

Opened https://github.com/microsoft/vscode-dev-containers/pull/1765 👍

**Comment by eitsupi** [comment]
Thanks for the quick update!

**Pull request merged**
