### PR TITLE
Add Tailscale devcontainer feature

### PR DESCRIPTION
**Pull request by mayakacz**
Adds the Tailscale devcontainer feature. cc @DentonGentry
Depends on https://github.com/tailscale/codespace/pull/6/files to merge with a new devcontainer feature for Tailscale.

### CODE REVIEW

**Comment by joshspicer** [comment]
Awesome! Feel free to nudge me here when https://github.com/tailscale/codespace/pull/6/files is merged so that we can merge this PR

**Comment by mayakacz** [comment]
It's merged!

**Review by samruddhikhandale — CHANGES_REQUESTED** [review]
Thanks, can you help resolve merge conflicts and then I'll help merge this PR?

**Review by samruddhikhandale — APPROVED** [review]
Awesome, thanks!

**Comment by samruddhikhandale** [comment]
Reverting this PR due to an issue. More details - https://github.com/devcontainers/devcontainers.github.io/pull/127#discussion_r1063757726 

@mayakacz Can you take a look at it? thanks!

**Pull request merged**
